### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by timcdlucas** [andrewzm/INLA#1]
Thank you very much for this!

Do you plan to keep this vaguely up to date?

**Comment by andrewzm** [comment]
Hi Tim! Sorry for the late reply. I updated it now but I don't intend to
keep it updated regularly, maybe once every few months (it's not meant to
be a mirror). If you need a constantly updated source I think you can
easily configure travis to get it directly from the INLA repo.

**Comment by timcdlucas** [comment]
No, every few months or so is perfectly fine. I'm using it for the same reason as you, just for testing purposes. So as long as it's not getting years and years old it's not at all a problem.

I couldn't get travis to install it directly from the INLA repo, but I don't really know what I'm doing.

Thanks again!
